### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by YeFei572** [JiaYuanfangDeveloper/flutter_getx_project_template#2]
1. 作者依赖中的oktoast感觉没有什么意义，因为`get`依赖自带toast弹窗功能。
2. 建议加入屏幕适配功能，适配功能是一个项目必须要有的。
3. 建议加入主题设置白天夜晚模式，该功能属于get的全局配置，适配方便且实用性强

**Comment by ilmari-code** [comment]
2.有屏幕适配了，在main.dart 中有做
1.3以后会加上

**Comment by YeFei572** [comment]
屏幕适配看到了，我以为你直接引入flutter_screen_utils这个包来做适配，没发现用的是flustar这个库，这个库有点杂 ，不需要的东西太多了 ，而且后面版本升级还要受限于这个库的版本，不太建议用这个库
